### ISSUE TITLE
number/integer response types - reporterapp or datums issue?

### ISSUE THREAD

**Issue by tbuckl** [thejunglejane/datums#8]
first, thanks for this great tool! 

i get an error on import from a "number" question (e.g. how many coffees did you have today), where i had answered "2.5"

i think this may be more of a poor specification on the part of the json export. or else, my limited understanding of how the question type response is decided. 

its the example for a number in the reporter json export data specification: 

https://gist.github.com/dbreunig/9315705

here's the trace, with a few print statements i stuck in to trace down the response that was causing the error:

``````
{u'questionPrompt': u'How many coffees did you have today?', u'uniqueIdentifier': u'644B2522-3E0C-4CFD-B7A4-5B3B7C3D8A11', u'numericResponse': u'2.5'}
response class:
<class 'datums.models.responses.NumericResponse'>
response column:
numeric_response
response:
2.5
Traceback (most recent call last):
  File "/Users/thomasbuckley/anaconda/bin/datums", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/Users/thomasbuckley/Projects/datums/bin/datums", line 79, in <module>
    main()
  File "/Users/thomasbuckley/Projects/datums/bin/datums", line 61, in main
    add.add_report(snapshot)
  File "/Users/thomasbuckley/Projects/datums/datums/pipeline/add.py", line 122, in add_report
    add_response(response, snapshot)
  File "/Users/thomasbuckley/Projects/datums/datums/pipeline/add.py", line 110, in add_response
    accessor.get_or_create_from_legacy_response(response, **ids)
  File "/Users/thomasbuckley/Projects/datums/datums/models/base.py", line 85, in get_or_create_from_legacy_response
    session.commit()
  File "/Users/thomasbuckley/anaconda/lib/python2.7/site-packages/sqlalchemy/orm/scoping.py", line 150, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/Users/thomasbuckley/anaconda/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 790, in commit
    self.transaction.commit()
  File "/Users/thomasbuckley/anaconda/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 392, in commit
    self._prepare_impl()
  File "/Users/thomasbuckley/anaconda/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 372, in _prepare_impl
    self.session.flush()
  File "/Users/thomasbuckley/anaconda/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2004, in flush
    self._flush(objects)
  File "/Users/thomasbuckley/anaconda/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2122, in _flush
    transaction.rollback(_capture_exception=True)
  File "/Users/thomasbuckley/anaconda/lib/python2.7/site-packages/sqlalchemy/util/langhelpers.py", line 60, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/Users/thomasbuckley/anaconda/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2086, in _flush
    flush_context.execute()
  File "/Users/thomasbuckley/anaconda/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 373, in execute
    rec.execute(self)
  File "/Users/thomasbuckley/anaconda/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 532, in execute
    uow
  File "/Users/thomasbuckley/anaconda/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 170, in save_obj
    mapper, table, update)
  File "/Users/thomasbuckley/anaconda/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 672, in _emit_update_statements
    execute(statement, multiparams)
  File "/Users/thomasbuckley/anaconda/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 914, in execute
    return meth(self, multiparams, params)
  File "/Users/thomasbuckley/anaconda/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/Users/thomasbuckley/anaconda/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/Users/thomasbuckley/anaconda/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1146, in _execute_context
    context)
  File "/Users/thomasbuckley/anaconda/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
    exc_info
  File "/Users/thomasbuckley/anaconda/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 199, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/Users/thomasbuckley/anaconda/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
    context)
  File "/Users/thomasbuckley/anaconda/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 450, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.DataError: (psycopg2.DataError) invalid input syntax for integer: "2.5"
LINE 1: UPDATE responses SET numeric_response='2.5' WHERE responses....
                                              ^
 [SQL: 'UPDATE responses SET numeric_response=%(numeric_response)s WHERE responses.id = %(responses_id)s'] [parameters: {'responses_id': 1937, 'numeric_response': u'2.5'}]```
``````

**Comment by thejunglejane** [comment]
Thanks @buckleytom! This is an oversight on my part. The postgres schema for the `numeric_responses` column of the `responses` table only accepts integers; I'll add float support!

**Comment by thejunglejane** [comment]
@buckleytom that should do it. I'd pull master, reinstall (in develop mode as per your other issue, which I'm looking into), and then teardown and setup your datums database again.

``` bash
$ datums --teardown
$ datums --setup
```

**Comment by tbuckl** [comment]
cool that did it!
