### ISSUE TITLE
need to run python setup.py develop for datums CLI

### ISSUE THREAD

**Issue by tbuckl** [thejunglejane/datums#9]
This is probably just a specific issue with how my environment is setup, but it may be helpful for other people to know? maybe not an open issue but not sure where to file it.  

When I setup with `python setup.py install` and then tried `datums --setup` I got `ImportError: No module named datums` - full trace below. 

however, with `python setup.py develop` the `datums` command line tools work fine.  

```
$ datums --teardown
Traceback (most recent call last):
  File "/Users/thomasbuckley/anaconda/bin/datums", line 4, in <module>
    __import__('pkg_resources').run_script('datums==0.0.2', 'datums')
  File "/Users/thomasbuckley/anaconda/lib/python2.7/site-packages/setuptools-18.0.1-py2.7.egg/pkg_resources/__init__.py", line 735, in run_script
  File "/Users/thomasbuckley/anaconda/lib/python2.7/site-packages/setuptools-18.0.1-py2.7.egg/pkg_resources/__init__.py", line 1659, in run_script
  File "/Users/thomasbuckley/anaconda/lib/python2.7/site-packages/datums-0.0.2-py2.7.egg/EGG-INFO/scripts/datums", line 8, in <module>

ImportError: No module named datums
```

**Comment by thejunglejane** [comment]
@buckleytom this one's fixed too. Pull master and reinstall with `python setup.py install` and test to make sure that it worked with `datums --version` _in a different directory_. You shouldn't see the `ImportError` anymore.

**Comment by tbuckl** [comment]
@thejunglejane nice, thanks!
